//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string phone_number { get; set; }
        public string fax { get; set; }
        public Nullable<bool> advertise { get; set; }
        public string img_url { get; set; }
    }
}
