//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchased_ad
    {
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public Nullable<float> discount { get; set; }
        public string specialty { get; set; }
        public string service { get; set; }
        public string img_url { get; set; }
        public int buyed_cupons { get; set; }
        public int cid { get; set; }
        public Nullable<int> client_id { get; set; }
        public int state { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<System.DateTime> purchase_time { get; set; }
        public string inst_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string website { get; set; }
    }
}
