//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchable_ad
    {
        public string name { get; set; }
        public string inst_name { get; set; }
        public decimal price { get; set; }
        public Nullable<float> discount { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string specialty { get; set; }
        public string service { get; set; }
        public int id { get; set; }
    }
}
