//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AdDescriptionName {
            get {
                return ResourceManager.GetString("AdDescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdDescriptionNameLength {
            get {
                return ResourceManager.GetString("AdDescriptionNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string AdDescriptionNameRequired {
            get {
                return ResourceManager.GetString("AdDescriptionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AdEndDateName {
            get {
                return ResourceManager.GetString("AdEndDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required.
        /// </summary>
        public static string AdEndDateNameRequired {
            get {
                return ResourceManager.GetString("AdEndDateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Image.
        /// </summary>
        public static string AdImageName {
            get {
                return ResourceManager.GetString("AdImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupon Title.
        /// </summary>
        public static string AdName {
            get {
                return ResourceManager.GetString("AdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdNameLength {
            get {
                return ResourceManager.GetString("AdNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string AdNameRequired {
            get {
                return ResourceManager.GetString("AdNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Price.
        /// </summary>
        public static string AdPreviousPriceName {
            get {
                return ResourceManager.GetString("AdPreviousPriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Price is required.
        /// </summary>
        public static string AdPreviousPriceNameRequired {
            get {
                return ResourceManager.GetString("AdPreviousPriceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string AdPriceName {
            get {
                return ResourceManager.GetString("AdPriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        public static string AdPriceNameRequired {
            get {
                return ResourceManager.GetString("AdPriceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string AdServiceName {
            get {
                return ResourceManager.GetString("AdServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdServiceNameLength {
            get {
                return ResourceManager.GetString("AdServiceNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name is required.
        /// </summary>
        public static string AdServiceNameRequired {
            get {
                return ResourceManager.GetString("AdServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string AdSpecialtyName {
            get {
                return ResourceManager.GetString("AdSpecialtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdSpecialtyNameLength {
            get {
                return ResourceManager.GetString("AdSpecialtyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty name is required.
        /// </summary>
        public static string AdSpecialtyNameRequired {
            get {
                return ResourceManager.GetString("AdSpecialtyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AdStartDateName {
            get {
                return ResourceManager.GetString("AdStartDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required.
        /// </summary>
        public static string AdStartDateNameRequired {
            get {
                return ResourceManager.GetString("AdStartDateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cupons.
        /// </summary>
        public static string AdTotalCuponsName {
            get {
                return ResourceManager.GetString("AdTotalCuponsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cupons is required.
        /// </summary>
        public static string AdTotalCuponsNameRequired {
            get {
                return ResourceManager.GetString("AdTotalCuponsNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired Cupons.
        /// </summary>
        public static string AquiredCupons {
            get {
                return ResourceManager.GetString("AquiredCupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ads.
        /// </summary>
        public static string BuyAds {
            get {
                return ResourceManager.GetString("BuyAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone number.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupon.
        /// </summary>
        public static string Cupon {
            get {
                return ResourceManager.GetString("Cupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupon image.
        /// </summary>
        public static string CuponImage {
            get {
                return ResourceManager.GetString("CuponImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupons.
        /// </summary>
        public static string Cupons {
            get {
                return ResourceManager.GetString("Cupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password required.
        /// </summary>
        public static string CurrentPasswordReq {
            get {
                return ResourceManager.GetString("CurrentPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart is empty.
        /// </summary>
        public static string EmptyCartNotif {
            get {
                return ResourceManager.GetString("EmptyCartNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in.
        /// </summary>
        public static string ExpiresIn {
            get {
                return ResourceManager.GetString("ExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Checkout.
        /// </summary>
        public static string FastCheckout {
            get {
                return ResourceManager.GetString("FastCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string InstitutionAddressName {
            get {
                return ResourceManager.GetString("InstitutionAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be under 250 characters.
        /// </summary>
        public static string InstitutionAddressNameLength {
            get {
                return ResourceManager.GetString("InstitutionAddressNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string InstitutionAddressNameRequired {
            get {
                return ResourceManager.GetString("InstitutionAddressNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise.
        /// </summary>
        public static string InstitutionAdvertiseName {
            get {
                return ResourceManager.GetString("InstitutionAdvertiseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string InstitutionCityName {
            get {
                return ResourceManager.GetString("InstitutionCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be under 50 characters.
        /// </summary>
        public static string InstitutionCityNameLength {
            get {
                return ResourceManager.GetString("InstitutionCityNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string InstitutionCityNameRequired {
            get {
                return ResourceManager.GetString("InstitutionCityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string InstitutionEmailName {
            get {
                return ResourceManager.GetString("InstitutionEmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string InstitutionEmailNameRequired {
            get {
                return ResourceManager.GetString("InstitutionEmailNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string InstitutionFaxName {
            get {
                return ResourceManager.GetString("InstitutionFaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InstitutionLabelName {
            get {
                return ResourceManager.GetString("InstitutionLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution name must be less than 50 characters.
        /// </summary>
        public static string InstitutionLabelNameLength {
            get {
                return ResourceManager.GetString("InstitutionLabelNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution name is required.
        /// </summary>
        public static string InstitutionLabelNameRequired {
            get {
                return ResourceManager.GetString("InstitutionLabelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string InstitutionLabelPhoneRequired {
            get {
                return ResourceManager.GetString("InstitutionLabelPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string InstitutionLatitudeName {
            get {
                return ResourceManager.GetString("InstitutionLatitudeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required.
        /// </summary>
        public static string InstitutionLatitudeNameRequired {
            get {
                return ResourceManager.GetString("InstitutionLatitudeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logintude.
        /// </summary>
        public static string InstitutionLongitudeName {
            get {
                return ResourceManager.GetString("InstitutionLongitudeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logintude is required.
        /// </summary>
        public static string InstitutionLongitudeNameRequired {
            get {
                return ResourceManager.GetString("InstitutionLongitudeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string InstitutionPhoneName {
            get {
                return ResourceManager.GetString("InstitutionPhoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string InstitutionWebsiteName {
            get {
                return ResourceManager.GetString("InstitutionWebsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website is required.
        /// </summary>
        public static string InstitutionWebsiteNameRequired {
            get {
                return ResourceManager.GetString("InstitutionWebsiteNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string ManagerLoginButtonName {
            get {
                return ResourceManager.GetString("ManagerLoginButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged.
        /// </summary>
        public static string ManagerLoginErrorAlreadyLogged {
            get {
                return ResourceManager.GetString("ManagerLoginErrorAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password.
        /// </summary>
        public static string ManagerLoginErrorInvalid {
            get {
                return ResourceManager.GetString("ManagerLoginErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string ManagerLoginHeaderName {
            get {
                return ResourceManager.GetString("ManagerLoginHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged.
        /// </summary>
        public static string ManagerLoginKeepLoggedName {
            get {
                return ResourceManager.GetString("ManagerLoginKeepLoggedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string ManagerLoginPasswordName {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ManagerLoginPasswordNameRequired {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string ManagerLoginPasswordPaceholder {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordPaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string ManagerLoginUserName {
            get {
                return ResourceManager.GetString("ManagerLoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string ManagerLoginUserNameRequired {
            get {
                return ResourceManager.GetString("ManagerLoginUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        public static string ManagerLoginUserPlaceholder {
            get {
                return ResourceManager.GetString("ManagerLoginUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not logged yet.
        /// </summary>
        public static string ManagerLogoutError {
            get {
                return ResourceManager.GetString("ManagerLogoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout done.
        /// </summary>
        public static string ManagerLogoutMsg {
            get {
                return ResourceManager.GetString("ManagerLogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password required.
        /// </summary>
        public static string NewPasswordReq {
            get {
                return ResourceManager.GetString("NewPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        public static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long.
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Sign in with Facebook.
        /// </summary>
        public static string SignInFacebook {
            get {
                return ResourceManager.GetString("SignInFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed Cupons.
        /// </summary>
        public static string SubscribedCupons {
            get {
                return ResourceManager.GetString("SubscribedCupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required.
        /// </summary>
        public static string UserNameReq {
            get {
                return ResourceManager.GetString("UserNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User picture.
        /// </summary>
        public static string UserPicture {
            get {
                return ResourceManager.GetString("UserPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
