//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AdDescriptionName {
            get {
                return ResourceManager.GetString("AdDescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdDescriptionNameLength {
            get {
                return ResourceManager.GetString("AdDescriptionNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string AdDescriptionNameRequired {
            get {
                return ResourceManager.GetString("AdDescriptionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AdEndDateName {
            get {
                return ResourceManager.GetString("AdEndDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required.
        /// </summary>
        public static string AdEndDateNameRequired {
            get {
                return ResourceManager.GetString("AdEndDateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Image.
        /// </summary>
        public static string AdImageName {
            get {
                return ResourceManager.GetString("AdImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupon Title.
        /// </summary>
        public static string AdName {
            get {
                return ResourceManager.GetString("AdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdNameLength {
            get {
                return ResourceManager.GetString("AdNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string AdNameRequired {
            get {
                return ResourceManager.GetString("AdNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Price.
        /// </summary>
        public static string AdPreviousPriceName {
            get {
                return ResourceManager.GetString("AdPreviousPriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Price is required.
        /// </summary>
        public static string AdPreviousPriceNameRequired {
            get {
                return ResourceManager.GetString("AdPreviousPriceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string AdPriceName {
            get {
                return ResourceManager.GetString("AdPriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        public static string AdPriceNameRequired {
            get {
                return ResourceManager.GetString("AdPriceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string AdServiceName {
            get {
                return ResourceManager.GetString("AdServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdServiceNameLength {
            get {
                return ResourceManager.GetString("AdServiceNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name is required.
        /// </summary>
        public static string AdServiceNameRequired {
            get {
                return ResourceManager.GetString("AdServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string AdSpecialtyName {
            get {
                return ResourceManager.GetString("AdSpecialtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string AdSpecialtyNameLength {
            get {
                return ResourceManager.GetString("AdSpecialtyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty name is required.
        /// </summary>
        public static string AdSpecialtyNameRequired {
            get {
                return ResourceManager.GetString("AdSpecialtyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AdStartDateName {
            get {
                return ResourceManager.GetString("AdStartDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required.
        /// </summary>
        public static string AdStartDateNameRequired {
            get {
                return ResourceManager.GetString("AdStartDateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cupons.
        /// </summary>
        public static string AdTotalCuponsName {
            get {
                return ResourceManager.GetString("AdTotalCuponsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cupons is required.
        /// </summary>
        public static string AdTotalCuponsNameRequired {
            get {
                return ResourceManager.GetString("AdTotalCuponsNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string ManagerLoginButtonName {
            get {
                return ResourceManager.GetString("ManagerLoginButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged.
        /// </summary>
        public static string ManagerLoginErrorAlreadyLogged {
            get {
                return ResourceManager.GetString("ManagerLoginErrorAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password.
        /// </summary>
        public static string ManagerLoginErrorInvalid {
            get {
                return ResourceManager.GetString("ManagerLoginErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string ManagerLoginHeaderName {
            get {
                return ResourceManager.GetString("ManagerLoginHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged.
        /// </summary>
        public static string ManagerLoginKeepLoggedName {
            get {
                return ResourceManager.GetString("ManagerLoginKeepLoggedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string ManagerLoginPasswordName {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ManagerLoginPasswordNameRequired {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string ManagerLoginPasswordPaceholder {
            get {
                return ResourceManager.GetString("ManagerLoginPasswordPaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string ManagerLoginUserName {
            get {
                return ResourceManager.GetString("ManagerLoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string ManagerLoginUserNameRequired {
            get {
                return ResourceManager.GetString("ManagerLoginUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        public static string ManagerLoginUserPlaceholder {
            get {
                return ResourceManager.GetString("ManagerLoginUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not logged yet.
        /// </summary>
        public static string ManagerLogoutError {
            get {
                return ResourceManager.GetString("ManagerLogoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout done.
        /// </summary>
        public static string ManagerLogoutMsg {
            get {
                return ResourceManager.GetString("ManagerLogoutMsg", resourceCulture);
            }
        }
    }
}
